# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prototype New.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from genericpath import exists
from typing import Dict
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox
from screeninfo import get_monitors
import os
import sys
import json
from time import sleep
import pigpio as GPIO
import threading
import Sensors

class Ui_Dialog(object):

    #Software

    h = None
    w = None
    Monitors = None


    DataTemplate = None
    ProgValues = None
    SelectedProgName = None
    SelectedProg = None
    Caliper_Value = None
    g_level = None
    g_reading = None
    g_bits = None

    Started = None

    #Hardware
    Caliper_Data = None
    Caliper_Clock = None
    Relay = None
    TempSensor = None
    

    def __init__(self):
        self.Monitors = get_monitors()
        self.h = self.Monitors[0].height
        self.w = self.Monitors[0].width
        self.ProgValues = {}
        self.SelectedProgName = ["Prog1","Prog2","Prog3","Prog4"]
        self.SelectedProg = 0
        self.DataTemplate = { "Moteur1": 250, "Température": 70, "Ventilateur": 700}
        self.Started = False

        self.getData()
        self.SetupPins()
        
    def SetupPins(self):
        self.Relay = 4
        self.Caliper_Data = 20
        self.Caliper_Clock = 21
        return



    def getRectPxWidth(self, px):
        width = self.w * (px/621)
        return int(width)

    def getRectPxHeight(self, px):
        height = self.h * (px/331)
        return int(height)



    def getData(self):
        Names = ["Prog1","Prog2","Prog3","Prog4"]
        if not os.path.exists("./Data"):
            os.makedirs("./Data")
            print("Directory Created")
        for i in Names:
            path = "./Data/" + i + ".json"
            if not os.path.exists(path):
                file = open(path , 'w')
                json.dump(self.DataTemplate, file, indent = 4)
                self.ProgValues[i] = self.DataTemplate
                print(self.ProgValues[i])
            else:
                with open(path) as Data_file:
                    Data = json.load(Data_file)
                self.ProgValues[i] = Data
                print(self.ProgValues[i])
    


    def UpdateFile(self):
        for i in self.SelectedProgName:
            path = "./Data/" + i + ".json"
            file = open(path , 'w')
            json.dump(self.ProgValues[i], file, indent = 4)

    def ExportToFile(self):
        try:
            path = QtWidgets.QFileDialog.getSaveFileName(self, 'Save File', filter = "Json File (*.json)")
            path = str(path[0])
            if path.endswith('.json'):
                file = open(path, 'w')
            else:
                file = open(path + ".json", 'w')
            json.dump(self.ProgValues[self.SelectedProgName[self.SelectedProg]], file, indent = 4)
        except:
            pass
    
    def LoadFile(self):
        try:
            path = QtWidgets.QFileDialog.getOpenFileName(self, "Open File", filter = "Json File (*.json)")
            with open(str(path[0])) as Data_file:
                Data = json.load(Data_file)
            self.ProgValues[self.SelectedProgName[self.SelectedProg]] = Data
            self.UpdateUIValues()
            self.UpdateFile()
        except:
            pass




    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(self.w, self.h)
        self.Main = QtWidgets.QTabWidget(Dialog)
        self.Main.setGeometry(QtCore.QRect(0, 0, self.w, self.h))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main.sizePolicy().hasHeightForWidth())
        self.Main.setSizePolicy(sizePolicy)
        self.Main.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Main.setObjectName("Main")
        self.Mesures = QtWidgets.QWidget()
        self.Mesures.setObjectName("Mesures")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Mesures)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(self.getRectPxWidth(70), self.getRectPxHeight(60), self.getRectPxWidth(241), self.getRectPxHeight(221)))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("Mesures actuelles :")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("Moteur :")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("Température :")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("Ventilateur :")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("Val Moteur1")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("Val Température")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setObjectName("Val Ventilateur")
        self.verticalLayout_2.addWidget(self.label_20)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Mesures)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(self.getRectPxWidth(350), self.getRectPxHeight(60), self.getRectPxWidth(241), self.getRectPxHeight(221)))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_10.setObjectName("Mesures Programmées")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_11.setObjectName("Moteur1")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setObjectName("Température")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName("Ventilateur")
        self.verticalLayout_3.addWidget(self.label_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_15.setText("")
        self.label_15.setObjectName("Blank")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName("Val Moteur1")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_18.setObjectName("Val Température")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setObjectName("Val Ventilateur")
        self.verticalLayout_4.addWidget(self.label_19)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Mesures)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(self.getRectPxWidth(40), self.getRectPxHeight(30), self.getRectPxWidth(541), self.getRectPxHeight(10)))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_9.setObjectName("Start Button")
        self.pushButton_9.setSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.pushButton_9.clicked.connect(self.StartButton)
        self.horizontalLayout_8.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_10.setObjectName("Stop Button")
        self.pushButton_10.setSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.pushButton_10.clicked.connect(self.StopButton)
        self.horizontalLayout_8.addWidget(self.pushButton_10)
        self.Main.addTab(self.Mesures, "")
        self.Programme = QtWidgets.QWidget()
        self.Programme.setObjectName("Programme")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Programme)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(self.getRectPxWidth(20), self.getRectPxHeight(10), self.getRectPxWidth(571), self.getRectPxHeight(281)))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Programme_S = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Programme_S.setEditable(False)
        self.Programme_S.setObjectName("Programme Sélection")
        self.Programme_S.addItem("")
        self.Programme_S.addItem("")
        self.Programme_S.addItem("")
        self.Programme_S.addItem("")
        self.Programme_S.currentIndexChanged['int'].connect(self.ComboBoxUpdate)
        self.horizontalLayout_3.addWidget(self.Programme_S)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("Load")
        self.pushButton_3.clicked.connect(self.LoadFile)
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("Export")
        self.pushButton_4.clicked.connect(self.ExportToFile)
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_21.setObjectName("Moteur1")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setObjectName("Val Moteur1 Spin")
        self.spinBox.setRange(200,2000)
        self.spinBox.setValue(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Moteur1"])
        self.spinBox.setSuffix(" RPM")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("Save")
        self.pushButton_5.clicked.connect(lambda i: self.SaveValues(0))
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setObjectName("Température")
        self.horizontalLayout_5.addWidget(self.label_23)
        self.spinBox_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.spinBox_3.setObjectName("Val Température Spin")
        self.spinBox_3.setSingleStep(0.1)
        self.spinBox_3.setRange(30,70)
        self.spinBox_3.setValue(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Température"])
        self.spinBox_3.setSuffix(" °C")
        self.horizontalLayout_5.addWidget(self.spinBox_3)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_7.setObjectName("Save")
        self.pushButton_7.clicked.connect(lambda i: self.SaveValues(2))
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_24.setObjectName("Ventilateur")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.spinBox_4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_4.setObjectName("Val Ventilateur Spin")
        self.spinBox_4.setRange(200,700)
        self.spinBox_4.setValue(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Ventilateur"])
        self.spinBox_4.setSuffix(" RPM")
        self.horizontalLayout_4.addWidget(self.spinBox_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_8.setObjectName("Save")
        self.pushButton_8.clicked.connect(lambda i: self.SaveValues(3))
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.Main.addTab(self.Programme, "")

        self.retranslateUi(Dialog)
        self.Main.setCurrentIndex(0)
        self.UpdateTimer = QtCore.QTimer()
        self.UpdateTimer.setInterval(100)
        self.UpdateTimer.timeout.connect(self.TimerUpdate)
        self.UpdateTimer.start()
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton_9, self.pushButton_10)
        Dialog.setTabOrder(self.pushButton_10, self.Programme_S)
        Dialog.setTabOrder(self.Programme_S, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.spinBox)
        Dialog.setTabOrder(self.spinBox, self.pushButton_5)
        Dialog.setTabOrder(self.pushButton_5, self.spinBox_3)
        Dialog.setTabOrder(self.spinBox_3, self.pushButton_7)
        Dialog.setTabOrder(self.pushButton_7, self.spinBox_4)
        Dialog.setTabOrder(self.spinBox_4, self.pushButton_8)
        Dialog.setTabOrder(self.pushButton_8, self.Main)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Mesures actuelles :"))
        self.label_2.setText(_translate("Dialog", "Moteur :"))
        self.label_4.setText(_translate("Dialog", "Température :"))
        self.label_5.setText(_translate("Dialog", "Ventilateur :"))
        self.label_7.setText(_translate("Dialog", "TextLabel"))
        self.label_9.setText(_translate("Dialog", "TextLabel"))
        self.label_20.setText(_translate("Dialog", "TextLabel"))
        self.label_10.setText(_translate("Dialog", "Mesures programmées"))
        self.label_11.setText(_translate("Dialog", "Moteur :"))
        self.label_13.setText(_translate("Dialog", "Température :"))
        self.label_14.setText(_translate("Dialog", "Ventilateur :"))
        self.label_16.setText(_translate("Dialog", str(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Moteur1"]) + " RPM"))
        self.label_18.setText(_translate("Dialog", str(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Température"]) + " °C"))
        self.label_19.setText(_translate("Dialog", str(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Ventilateur"]) + " RPM"))
        self.pushButton_9.setText(_translate("Dialog", "Start"))
        self.pushButton_10.setText(_translate("Dialog", "Stop"))
        self.Main.setTabText(self.Main.indexOf(self.Mesures), _translate("Dialog", "Mesures"))
        self.Programme_S.setItemText(0, _translate("Dialog", "P1"))
        self.Programme_S.setItemText(1, _translate("Dialog", "P2"))
        self.Programme_S.setItemText(2, _translate("Dialog", "P3"))
        self.Programme_S.setItemText(3, _translate("Dialog", "P4"))
        self.pushButton_3.setText(_translate("Dialog", "Load"))
        self.pushButton_4.setText(_translate("Dialog", "Export"))
        self.label_21.setText(_translate("Dialog", "Moteur :"))
        self.pushButton_5.setText(_translate("Dialog", "Save"))
        self.label_23.setText(_translate("Dialog", "Température :"))
        self.pushButton_7.setText(_translate("Dialog", "Save"))
        self.label_24.setText(_translate("Dialog", "Ventilateur :"))
        self.pushButton_8.setText(_translate("Dialog", "Save"))
        self.Main.setTabText(self.Main.indexOf(self.Programme), _translate("Dialog", "Programme"))

    def ComboBoxUpdate(self):
        self.SelectedProg = self.Programme_S.currentIndex()
        self.UpdateUIValues()

    def UpdateUIValues(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_16.setText(_translate("Dialog", str(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Moteur1"]) + " RPM"))
        self.spinBox.setValue(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Moteur1"])
        self.label_18.setText(_translate("Dialog", str(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Température"]) + " °C"))
        self.spinBox_3.setValue(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Température"])
        self.label_19.setText(_translate("Dialog", str(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Ventilateur"]) + " RPM"))
        self.spinBox_4.setValue(self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Ventilateur"])
    
    def UpdateSensorValues(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_16.setText(_translate("Dialog", str() + " RPM"))
        self.label_18.setText(_translate("Dialog", str(self.SensorValues["Température"]) + " °C"))
        self.label_19.setText(_translate("Dialog", str() + " RPM"))

    def SaveValues(self,Button):
        if Button == 0:
            self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Moteur1"] = self.spinBox.value()
        elif Button == 2:
            self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Température"] = self.spinBox_3.value()
        elif Button == 3:
            self.ProgValues[self.SelectedProgName[self.SelectedProg]]["Ventilateur"] = self.spinBox_4.value()         
        self.UpdateUIValues()
        self.UpdateFile()

    def TimerUpdate(self):
        self.SensorValues = Sensors.GetSensorValues()
        if self.Started == True:
            self.Working()
        print("Looping")

    def StartButton(self):
        self.Started = True
        print(self.Started)

    def StopButton(self):
        self.Started = False
        print(self.Started)

    def Working(self):
        if self.SensorValues["Sécurisé"] == True:
            print("Working")
        else:
            self.Started = False
            self.SendError()

    def SendError(self):
        self.msg = QMessageBox()
        self.msg.setIcon(QMessageBox.Critical)
        self.msg.setText("Alerte de sécurité \nVeuillez fermer l'entonnoire pour continuer")
        self.msg.setWindowTitle("Entonnoir ouvert")
        self.msg.exec_()

    def ResetComposants(self):
        self.Relay.off()


#Ckeck each time timer goes if open or not 